Simplon_App_bancaire_Django/Bamk/Bamk/urls.py
# Bank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='user')),
    path('chat/', include('chat.urls')),
    path('news/', include('news.urls')),
    path('loan/', include('loan.urls')),
    path('', RedirectView.as_view(url='home')),
    path('__reload__/', include('django_browser_reload.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Simplon_App_bancaire_Django/Bamk/user/urls.py
from django.urls import path
from user.views import (
    HomeView,
    UserRegistrationView,
    UserLoginView,
    ClientDashboardView,
    AdvisorDashboardView,
    ListClientView,
    ClientFileView,
)
from django.contrib.auth.views import LogoutView
from django.urls import include, path

app_name = 'user'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('client/', ClientDashboardView.as_view(), name='client_dashboard'),
    path('advisor/', AdvisorDashboardView.as_view(), name='advisor_dashboard'),
    path('list_client/', ListClientView.as_view(), name='list_clients'),
    path('client/<int:pk>/file/', ClientFileView.as_view(), name='client_file'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("__reload__/", include("django_browser_reload.urls")),
]

Simplon_App_bancaire_Django/Bamk/theme/templates/back_button.html
<div class="mt-8 flex justify-start">
    <a href="javascript:history.back()" class="px-4 py-2 bg-white text-navy rounded-lg shadow hover:bg-gray-400 transition">
        ← Back
    </a>
</div>

Simplon_App_bancaire_Django/Bamk/theme/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}BAMK{% endblock %}</title>
    <link href="{% static 'css/dist/styles.css' %}" rel="stylesheet">
</head>
<body class="bg-white text-gray-900">

    <!-- Navigation -->
    <nav class="bg-navy text-white p-4 shadow-md">
        <div class="container mx-auto flex justify-between items-center">
            <a href="{% url 'user:home' %}" class="text-xl font-bold">BAMK</a>
            <ul class="flex space-x-4">
                <li><a href="{% url 'user:login' %}" class="hover:text-lightblue">Login</a></li>
                <li><a href="{% url 'user:register' %}" class="hover:text-lightblue">Register</a></li>
            </ul>
        </div>
    </nav>

    <!-- Contenu principal -->
    <main class="container mx-auto p-6">
        {% block content %}{% endblock %}
    </main>

    <footer class="bg-navy text-white py-10">
        <div class="container mx-auto px-6 lg:px-20 mt-10 grid grid-cols-1 md:grid-cols-2 gap-8 text-gray-400 text-sm">
            <!-- Legal Information -->
            <div class="md:col-span-2">
                <p>© 2025 Bamk</p>
                <p>Bamk, Inc. – Registered in Delaware</p>
                <p>Headquarters: 100 Wall Street, Suite 500, New York, NY 10005, USA</p>
                <p>FDIC Member – Equal Housing Lender</p>
            </div>
        </div>
    </footer>
    

</body>
</html>

Simplon_App_bancaire_Django/Bamk/theme/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}BAMK{% endblock %}</title>
        <link href="{% static 'css/dist/styles.css' %}" rel="stylesheet">
    </head>
    <body class="bg-white text-gray-900">

        <!-- Navigation -->
        <nav class="bg-navy text-white p-4 shadow-md">
            <div class="container mx-auto flex justify-between items-center">
                <a class="text-xl font-bold">BAMK</a>
                <ul class="flex space-x-4">
                    <form action="{% url 'user:login' %}" method="post">
                        {% csrf_token %}
                        <button type='submit'class="hover:text-[#00bfae] transition duration-300">Logout</button>
                    </form>
                </ul>
            </div>
        </nav>

        <!-- Main Content -->
        <main class="container mx-auto p-6">
            {% block content %}{% endblock %}
        </main>

    <!-- Footer -->
        <footer class="bg-navy text-white py-10">
            <div class="container mx-auto px-6 lg:px-20 mt-10 grid grid-cols-1 md:grid-cols-2 gap-8 text-gray-400 text-sm">
                <!-- Legal Information -->
                <div class="md:col-span-2">
                    <p>© 2025 Bamk</p>
                    <p>Bamk, Inc. – Registered in Delaware</p>
                    <p>Headquarters: 100 Wall Street, Suite 500, New York, NY 10005, USA</p>
                    <p>FDIC Member – Equal Housing Lender</p>
                </div>
            </div>
        </footer>

    </body>
</html>